drop database ESCOLA;
CREATE DATABASE ESCOLA;

USE ESCOLA;

DROP TABLE ALUNO;

CREATE TABLE ALUNO(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100),
	EMAIL VARCHAR(100),
	TELEFONE VARCHAR(20),
	ALTURA DOUBLE(3,2),
	APROVADO BOOLEAN,
	SEXO ENUM ('M','F'),
	CIDADE VARCHAR(100),
	CPF VARCHAR(20) UNIQUE,
	UNIQUE INDEX(NOME,SEXO)
);

DROP TABLE PROFESSOR;

CREATE TABLE PROFESSOR(
	CODIGO INT,
	NOME VARCHAR(100) NOT NULL UNIQUE,
    PRIMARY KEY(CODIGO)
);

CREATE TABLE Turma (
	id INT NOT NULL ,
	inicio DATETIME ,
	fim DATETIME ,
	observacoes LONGTEXT ,
	PRIMARY KEY ( id )
)

INSERT INTO ALUNO (NOME,EMAIL,TELEFONE,ALTURA,APROVADO,SEXO,CIDADE,CPF) VALUES ("ATILA","ATILA@CEPEP.COM","123456","1.63",TRUE,"F","FORTALEZA","78934613212");
INSERT INTO ALUNO (NOME,EMAIL,TELEFONE,ALTURA,APROVADO,SEXO,CIDADE,CPF) VALUES ("ANDRE","ANDRE@CEPEP.COM","123456","1.75",TRUE, "M","FORTALEZA","54654654654" );
INSERT INTO ALUNO (NOME,EMAIL,TELEFONE,ALTURA,APROVADO,SEXO,CIDADE,CPF) VALUES ("LEONARDO","LEONARDO@CEPEP.COM","123456","1.77",TRUE, "M","FORTALEZA","546546534543465");
INSERT INTO ALUNO (NOME,EMAIL,TELEFONE,ALTURA,APROVADO,SEXO,CIDADE,CPF) VALUES ("PLATINI","PLATINI@CEPEP.COM","123456","1.83",TRUE, "M","FORTALEZA","546542322654");
INSERT INTO ALUNO (NOME,EMAIL,TELEFONE,ALTURA,APROVADO,SEXO,CIDADE,CPF) VALUES ("JOSE","JOSE@CEPEP.COM","123456","1.68",FALSE, "M","FORTALEZA","5465465445454");
INSERT INTO ALUNO (NOME,EMAIL,TELEFONE,ALTURA,APROVADO,SEXO,CIDADE,CPF) VALUES ("ANTONIO","ANTONIO@CEPEP.COM","123456","1.69",FALSE, "M","FORTALEZA","5465465225554");

INSERT INTO PROFESSOR VALUES (1,"ARISTENIO");
INSERT INTO PROFESSOR VALUES (2,"MARCELO");
INSERT INTO PROFESSOR VALUES (3,"VALDO");

DELETE FROM ALUNO;

SELECT * FROM ALUNO;

SELECT NOME, EMAIL FROM ALUNO;

SELECT * FROM ALUNO,PROFESSOR;

SELECT a.NOME,p.NOME FROM ALUNO a ,PROFESSOR p;

SELECT a.NOME as NOME_ALUNO,p.NOME as NOME_PROFESSOR FROM ALUNO as a ,PROFESSOR as p;

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE A.ALTURA > 1.80;

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE A.ALTURA = 1.75;

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE A.ALTURA <> 1.75;

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE A.ALTURA <= 1.75;

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE A.ALTURA > 1.75;

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE A.ALTURA >= 1.75;

SELECT A.NOME AS NOME_ALUNO, A.APROVADO FROM ALUNO AS A WHERE A.APROVADO IS TRUE;

SELECT A.NOME AS NOME_ALUNO, A.APROVADO FROM ALUNO AS A WHERE A.APROVADO IS FALSE;

SELECT A.NOME AS NOME_ALUNO, A.APROVADO FROM ALUNO AS A WHERE A.APROVADO = 0;

SELECT A.NOME AS NOME_ALUNO, A.APROVADO FROM ALUNO AS A WHERE A.NOME IS NOT NULL;

SELECT A.NOME AS NOME_ALUNO, A.APROVADO FROM ALUNO AS A WHERE A.NOME IS NULL;

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE A.ALTURA BETWEEN 1.70 AND 1.80;

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE A.ALTURA <= 1.80 AND A.ALTURA >= 1.70;

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE A.ALTURA NOT BETWEEN 1.70 AND 1.80;

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE A.NOME LIKE "ANTONIO";

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE A.NOME LIKE "ANTO%";

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE A.NOME LIKE "%L%";

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE A.ALTURA IN (1.75, 1.83, 1.69);

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE A.ALTURA NOT IN (1.75, 1.83, 1.69);

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE !(A.ALTURA = 1.75);

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE NOT A.ALTURA = 1.75;

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE (A.ALTURA > 1.70) AND (APROVADO IS TRUE) AND (A.NOME LIKE "A%");

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE (A.ALTURA > 1.70) && (APROVADO IS TRUE) && (A.NOME LIKE "A%");

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE ((A.ALTURA > 1.70) OR (APROVADO IS TRUE)) AND (A.NOME LIKE "A%"); 

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE A.ALTURA > 1.70 XOR A.APROVADO IS TRUE;

SELECT * FROM ALUNO ORDER BY NOME;

SELECT * FROM ALUNO ORDER BY ALTURA,NOME;

SELECT * FROM ALUNO ORDER BY NOME DESC;

SELECT * FROM ALUNO ORDER BY NOME ASC;

SELECT COUNT(*) FROM ALUNO;

SELECT AVG(ALTURA) FROM ALUNO;

SELECT SUM(ALTURA) FROM ALUNO;

SELECT MAX(ALTURA) FROM ALUNO;

SELECT MIN(ALTURA) FROM ALUNO;

SELECT VARIANCE(ALTURA) FROM ALUNO;

ALTER TABLE ALUNO ADD SEXO VARCHAR(1) NOT NULL;

UPDATE ALUNO SET SEXO = "M";

INSERT INTO ALUNO (NOME,EMAIL,TELEFONE,ALTURA,APROVADO,SEXO,CIDADE,CPF) VALUES ("MARIA","MARIA@CEPEP.COM","123456","1.65",TRUE,"F","FORTALEZA","5465465346554");
INSERT INTO ALUNO (NOME,EMAIL,TELEFONE,ALTURA,APROVADO,SEXO,CIDADE,CPF) VALUES ("JOAQUINA","JOAQUINA@CEPEP.COM","123456","1.63",TRUE, "f","FORTALEZA","546546534654");

SELECT * FROM ALUNO WHERE SEXO LIKE "M";
SELECT * FROM ALUNO WHERE SEXO LIKE "F";

SELECT APROVADO, COUNT(*) FROM ALUNO GROUP BY APROVADO;

SELECT SEXO,APROVADO, COUNT(*) FROM ALUNO GROUP BY SEXO,APROVADO;

SELECT COUNT(*) AS TOTAL_APROVADO FROM ALUNO WHERE APROVADO IS TRUE AND NOME LIKE "A%" XOR "%A" GROUP BY APROVADO;

SELECT * FROM ALUNO;

SELECT DISTINCT(NOME) FROM ALUNO; 

ALTER TABLE ALUNO ADD CIDADE VARCHAR(100) NOT NULL;

UPDATE ALUNO SET CIDADE = "FORTALEZA";

UPDATE ALUNO SET CIDADE = "JUAZEIRO" WHERE NOME LIKE "A%";

SELECT DISTINCT(CIDADE) FROM ALUNO;

SELECT * FROM ALUNO LIMIT 5;

SELECT COUNT(*) FROM ALUNO;

SELECT * FROM ALUNO ORDER BY NOME;

SELECT * FROM ALUNO ORDER BY NOME LIMIT 2;
SELECT * FROM ALUNO ORDER BY NOME LIMIT 0,2;
SELECT * FROM ALUNO ORDER BY NOME LIMIT 2,2;
SELECT * FROM ALUNO ORDER BY NOME LIMIT 4,2;
SELECT * FROM ALUNO ORDER BY NOME LIMIT 6,2;

select * from aluno;
select sexo, count(*) from aluno group by sexo;
select cidade, count(*) from aluno group by cidade;

select altura, count(*) from aluno group by altura having altura>1.70;
select altura, count(*) from aluno group by altura having count(altura)>1;

ALTER TABLE ALUNO ADD CPF VARCHAR(20) UNIQUE;

UPDATE ALUNO SET CPF = "1345678911" WHERE NOME = "ANDRE";

UPDATE ALUNO SET CPF = "1345678911" WHERE NOME = "JOSE";

SELECT NOME,CPF FROM ALUNO;

DELETE FROM ALUNO WHERE NOME="ANTONIO";

ALTER TABLE ALUNO ADD UNIQUE(NOME);

ALTER TABLE ALUNO ADD PRIMARY KEY(CPF);

ALTER TABLE ALUNO ADD UNIQUE(NOME, SEXO);

SELECT * FROM ALUNO ORDER BY NOME;

DROP INDEX NOME_3 ON ALUNO;

DROP INDEX CPF ON ALUNO;

CREATE TABLE TURMA(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
	TITULO VARCHAR(255),
	INICIO DATETIME,
	FIM DATETIME,
	OBSERVACOES TEXT
);

INSERT INTO TURMA (TITULO,INICIO,FIM) VALUES ("FORMACAO JAVA I","2014-07-05","2015-01-10");
INSERT INTO TURMA (TITULO,INICIO,FIM) VALUES ("NOTEBOOK","2014-07-05","2015-01-10");

CREATE TABLE ALUNO_TURMA(
	ALUNO_ID BIGINT NOT NULL,
	TURMA_ID BIGINT NOT NULL,
	PRIMARY KEY(ALUNO_ID,TURMA_ID),
	FOREIGN KEY(ALUNO_ID) REFERENCES ALUNO(ID),
	FOREIGN KEY(TURMA_ID) REFERENCES TURMA(ID)
);

INSERT INTO ALUNO_TURMA VALUES(1,1);
INSERT INTO ALUNO_TURMA VALUES(2,1);
INSERT INTO ALUNO_TURMA VALUES(3,1);
INSERT INTO ALUNO_TURMA VALUES(4,1);
INSERT INTO ALUNO_TURMA VALUES(5,1);
INSERT INTO ALUNO_TURMA VALUES(6,1);

INSERT INTO ALUNO_TURMA VALUES(1,2);
INSERT INTO ALUNO_TURMA VALUES(2,2);
INSERT INTO ALUNO_TURMA VALUES(3,2);


SELECT A.NOME, T.TITULO 
FROM ALUNO A, TURMA T, ALUNO_TURMA A_T 
WHERE A.ID = A_T.ALUNO_ID AND A_T.TURMA_ID = T.ID AND T.ID = 1;

CREATE TABLE NOTA(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
	ALUNO_ID BIGINT NOT NULL,
	TURMA_ID BIGINT NOT NULL,
	NOTA DECIMAL (4,2),
	FOREIGN KEY(ALUNO_ID) REFERENCES ALUNO(ID),
	FOREIGN KEY(TURMA_ID) REFERENCES TURMA(ID)
);

INSERT INTO NOTA (ALUNO_ID,TURMA_ID,NOTA) VALUES (1,1,8);
INSERT INTO NOTA (ALUNO_ID,TURMA_ID,NOTA) VALUES (2,1,10);
INSERT INTO NOTA (ALUNO_ID,TURMA_ID,NOTA) VALUES (3,1,7);
INSERT INTO NOTA (ALUNO_ID,TURMA_ID,NOTA) VALUES (4,1,8);
INSERT INTO NOTA (ALUNO_ID,TURMA_ID,NOTA) VALUES (5,1,9);
INSERT INTO NOTA (ALUNO_ID,TURMA_ID,NOTA) VALUES (6,1,6);

SELECT * FROM NOTA;

SELECT AVG(NOTA) FROM NOTA WHERE TURMA_ID = 1;

SELECT * FROM NOTA AS N1 WHERE N1.NOTA > (
	SELECT AVG(N2.NOTA) FROM NOTA AS N2 
	WHERE N2.TURMA_ID = 1
);

SELECT ALUNO.NOME,TURMA.TITULO,N1.NOTA FROM NOTA AS N1,ALUNO,TURMA 
	WHERE ALUNO.ID = N1.ALUNO_ID AND TURMA.ID = N1.TURMA_ID AND N1.NOTA > (
		SELECT AVG(N2.NOTA) FROM NOTA AS N2 
		WHERE N2.TURMA_ID = 1
);